### ISSUE TITLE
CFN Template fails to create

### ISSUE THREAD

**Issue by sebsto** [amazon-archives/amediamanager#1]
Sub stack #1 is OK : AMM-VPCScaffold
Sub Stack #2 is OK : AMM-AppResources

Sub Stack #3 fails with "The following resource(s) failed to create: [App1]."
Reason : "Parameters: [DockerKey] must have values"

I guess you're working on a Docker based version and current code in GitHub is not stable. Thoughts ?

**Comment by evandbrown** [comment]
Hi Seb,

Using the `master` branch should work fine. `DockerKey` is only in the `docker` branch which is experimental. You can also choose to stage the CFN templates in your own bucket and override the locations via the `ResourcesTemplate Key` etc params in https://github.com/awslabs/amediamanager/blob/docker/cfn/vpc/amm-master.cfn.json

**Comment by ChrisPetr0** [comment]
Evan,
I'm having the same problem as Sebsto on the master branch.  It fails at the exact same spot as above with the same error (I'm working on part 2 of your blog series).  I'm looking through everything trying to figure that out.  I just wanted to let you know I was having the same problem on the master branch.

I validated in my cloned git respository that indeed amm-master.cfn.json has no reference to "dockerkey" anywhere.

I'll post back if I figure it out.  

Thanks,

Chris

**Comment by evandbrown** [comment]
Hi Chris,

Thanks for pointing this out. `amm-master.cfn.json` references the child templates stored in an S3 bucket, and it looks like I pushed out a bad version previously. I just re-pushed and confirmed that the stack runs correctly. Hope that helps!

Evan

**Comment by ChrisPetr0** [comment]
Evan,
Thanks for the quick reply and fix.  It now runs completely with success.  Thanks for the great content as well!

Chris
